version: '3.1'

services:

  web:
    build: docker/web
    ports:
      - "8000:80"
    volumes:
      - ".:/var/www/html"
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=ufscar
      - MYSQL_PASSWORD=ufscar
      - MYSQL_DATABASE=dps
    volumes:
      - "db:/var/lib/mysql"

volumes:

  db:
    driver: local
