#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

# first arg is `composer` or `artisan`
if [[ $1 eq "artisan" ]]; then
	set -- php "$@"
fi

exec "$@"